# Generated by Django 5.2.15 on 2026-07-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyrun', '0003_poke_bank_gamereward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedevent',
            name='event_type',
            field=models.CharField(choices=[('contribution', '저축'), ('warning', '경고'), ('cheer', '응원'), ('penalty', '약속금'), ('badge', '배지'), ('mission', '미션'), ('join', '참여'), ('group', '그룹'), ('poke', '찌르기'), ('game', '게임보상'), ('bank', '은행연동')], max_length=20),
        ),
    ]
