# Generated by Django 5.2.15 on 2026-07-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyrun', '0004_alter_feedevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rungroup',
            name='room_mode',
            field=models.CharField(choices=[('challenge', '목표 챌린지'), ('account', '모임통장')], default='challenge', max_length=20),
        ),
    ]
